// import Partners from "@/components/pages/index/partners";
import Clients from "@/components/pages/index/clients";
import Crm from "@/components/pages/index/crm/crm";
import Outsource from "@/components/pages/index/outsource";
import Priorities from "@/components/pages/index/priorities";
import Start from "@/components/pages/index/start/start";
import { Metadata } from "next";
import Contacts from "@/components/pages/contacts";
import About from "@/components/pages/index/about";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Lawity колл-центр",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="bg-light-gray flex flex-col items-center relative">
      <Image
        src='/start/dots.svg'
        className='hidden lg:block absolute top-0 right-0'
        alt='Start'
        // width={400}
        // height={385}
        width={964}
        height={582}
      />
      <Start />
      {/* <Priorities /> */}
      <About />
      <Clients />
      <Outsource />
      <Crm />
      {/* <Partners /> */}
      <Contacts />
    </main>
  );
}
