import Clients from "@/components/pages/index/clients";
import Outsource from "@/components/pages/index/outsource";
import Priorities from "@/components/pages/index/priorities";
import Start from "@/components/pages/index/start";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Lawity колл-центр",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className=" light-gray flex flex-col items-center">
      <Start />
      <Priorities />
      <Clients />
      <Outsource />
    </main>
  );
}
